# Generated by Django 3.0 on 2020-12-20 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_plantdetails_transactiondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('txn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('txn_amount', models.FloatField()),
                ('txn_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantdetails',
            name='plant_count',
        ),
        migrations.RemoveField(
            model_name='plantdetails',
            name='plant_info',
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='plant_image',
            field=models.ImageField(blank=True, null=True, upload_to='static_cdn/img'),
        ),
        migrations.AddField(
            model_name='plantdetails',
            name='plant_price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='plant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PlantDetails'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
